### ISSUE TITLE
Problem with Latest Node Versions (4.2.1, 4.1.1)

### ISSUE THREAD

**Issue by Hunga1** [paypal/nemo-example-app#12]
When running the `grunt automation` command, a browser instance is created, but isn't driven by the tests. The tests ultimately fail from exceeding timeout time. The error message output is:
`Uncaught Error: Timed out waiting for the WebDriver server at http://127.0.0.1:41901/hub`

This problem was observed with both Node v4.1.1 and Node v4.2.1 (latest). I was able to successfully run the tests using an older environment, Node v0.10.36, following the same setup steps outlined by the project's README.md. I am running this all on Ubuntu 15.04 64-bit with Firefox 41.0.2 (latest).

**Comment by grawk** [comment]
Hi @Hunga1 I would bet that Firefox 41.0.2 is incompatible with the version of selenium-webdriver in nemo@v1.0.x. selenium-webdriver@v2.44.1 requires an older version of Firefox. Currently the latest selenium-webdriver (v2.46) is available in nemo@v1.1.0-alpha. Please see the following document:
https://github.com/paypal/nemo-docs/blob/master/upgrade-to-1.1.md

I will reproduce an Ubuntu environment today or tomorrow and verify this. But I'm pretty sure that's the issue.

**Comment by grawk** [comment]
I used the alpha versions of nemo and nemo-view on Ubuntu 14.04, Firefox 39. I'm able to automate this Firefox version with no problem. I suspect it is the webdriver version as mentioned above. I'll wait for you to respond @Hunga1 before closing this.

**Comment by Hunga1** [comment]
I installed Firefox 39.0.3 and tried again with node v4.2.1 (latest), but the tests failed. I noticed when I was using `npm install` with node v4.2.1/npm v2.14.7 that nemo v1.0.6 and selenium 2.44.0 were being fetched, but `npm install` with node v0.10.36/npm v1.4.28, nemo v1.1.0-alpha and selenium 2.46.0 were being fetched.

**Comment by grawk** [comment]
If you see versions of nemo that match your package.json in each version of node where you try and install, then it sounds like things are working as they should. Can I go ahead and close this or is there something amiss?

**Comment by Hunga1** [comment]
Yes, all is working well. Thanks for the help. Go ahead and close the issue.
